### ISSUE TITLE
Bug pertty 模式 request 数据包显示不完全

### ISSUE THREAD

**Issue by kenyon-wong** [saoshao/DetSql#4]
request 在 pertty 模式下，下拉进度条到底，数据包显示不完全

![图片](https://github.com/user-attachments/assets/e55cd0bb-bdcf-4a0c-9ad3-a7814167ff6e)

**Comment by saoshao** [comment]
临时解决方案，发送到repeater模块查看；后续进行改进

**Comment by saoshao** [comment]
1.3中已解决

**Comment by kenyon-wong** [comment]
感谢！

close #4
