### ISSUE TITLE
功能建议: 支持处理经过 Proxy 规则处理后的数据包

### ISSUE THREAD

**Issue by kenyon-wong** [saoshao/DetSql#5]
目前插件直接处理原始数据包进行 SQL 注入检测。建议在检测前，先应用 Burp Suite 的 [HTTP Match and Replace Rules] 规则集对数据包进行预处理。

原因:
1. 对于复杂的数据包，直接进行 SQL 注入检测可能会产生误报
2. 使用 Proxy 的替换规则可以先清理和标准化数据包
3. 这样可以提高检测的准确性和效率

预期效果:
1. 插件能够获取经过 Proxy 规则处理后的数据包
2. 基于处理后的数据包进行 SQL 注入检测
3. 减少复杂数据包带来的误报

**Comment by saoshao** [comment]
可处理使用替换规则后的数据包
![f065932477aef6ef48524691749185f](https://github.com/user-attachments/assets/89103871-1584-4747-9f02-fb08f38e29b7)

**Comment by kenyon-wong** [comment]
感谢！

close #5
