### ISSUE TITLE
功能建议: 结果列表支持排序功能

### ISSUE THREAD

**Issue by kenyon-wong** [saoshao/DetSql#6]
目前结果展示区域(左上)的列表不支持排序功能。

当 DetSQL 扫描的数据包很多时，能按照 [VulnState] 列进行排序会更加方便进行验证。

建议增加列表排序功能,特别是按 [VulnState] 列进行排序。

**Comment by saoshao** [comment]
排序已添加

**Comment by kenyon-wong** [comment]
感谢你的快速响应和实现！👍

我已经看到新增的排序功能，这确实大大提升了使用体验，尤其是在处理大量数据包时更加方便。

再次感谢！

fix #6
