### ISSUE TITLE
功能建议: 支持结果列表多选操作及右键菜单联动功能

### ISSUE THREAD

**Issue by kenyon-wong** [saoshao/DetSql#7]
目前结果列表(左上区域)不支持多选数据包及批量操作。

建议增加多选功能并提供右键菜单，实现与其他 Burp 插件(如 SQLMap4Burp++)的联动，方便进行批量验证或者完整的保存数据包。

**Comment by saoshao** [comment]
单个请求可发到别的插件进行操作
