### ISSUE TITLE
功能建议: 完整保存所有payload测试日志

### ISSUE THREAD

**Issue by kenyon-wong** [saoshao/DetSql#8]
当前插件只能查看，插件识别出来的注入点参数相应的数据包。

希望能够增加完整保存所有payload的测试日志：
- 插件判断存在SQLi的数据包中，非注入点参数对应的测试日志
- 插件判断不存在SQLi的数据包中，所有参数的测试日志

理由：
- 方便人工二次研判： 通过记录所有参数的测试日志，即使插件没有检测到SQL注入，我们也能进行人工二次研判。
- 有限支持一些邪教用法：在特定情况下，能够应急满足一些邪教用法（如任意文件读取）

**Comment by saoshao** [comment]
在logger中查看所有测试日志
