### ISSUE TITLE
orderby误报较大

### ISSUE THREAD

**Issue by hackd0g** [saoshao/DetSql#9]
长度一样  都能判断为转入
![image](https://github.com/user-attachments/assets/9fa5f32c-0d0d-463d-9eb3-e79772c15ccf)
![image](https://github.com/user-attachments/assets/d16ca072-ff59-452f-9edd-a5dfdb0d0462)

**Comment by saoshao** [comment]
截图多截点，后面similiarity这一栏显示多少

**Comment by saoshao** [comment]
但是orderby类型的确有一点历史问题需要处理
